/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mecanica;

import composite.CompuestoRecambio;
import composite.ElementoRecambio;
import composite.IRecambio;
import composite.Llanta;
import composite.Tornillo;
import java.awt.Graphics;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sebas
 */
public final class Sistema extends javax.swing.JFrame {

    /**
     * Creates new form Sistema
     */
    public Sistema() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);

        cargarTornillos();
        cargarLlantas();
        cargarValvulas();
        cargarNeumaticos();
        cargarRuedas();
        cargarRepuestos();
        cargarComponentes();

        seleccionarTornillo();
        seleccionarLlanta();
        seleccionarValvula();
        seleccionarNeumatico();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/imagenes/fondoSesion.png"));
        Image image = icon.getImage();
        jDesktopPane1 = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        JpnlInsersion1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jcbxRespuestos = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jtxtRepuestoCodigo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jtxtRepuestoMarca = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jtxtRepuestoPrecio = new javax.swing.JTextField();
        jtxtRepuestoTamaño = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jtxtRepuestoTipo = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jbtnAñadirRepuesto = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        JpnlInsersion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jcbxComponentes = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jtxtComponenteCodigo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxtComponenteMarca = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtxtComponentePrecio = new javax.swing.JTextField();
        jtxtComponenteTamaño = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jbtnConstruirComponente = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jlblTituloTornillos = new javax.swing.JLabel();
        jlblTituloLlantas = new javax.swing.JLabel();
        jlblTituloValvulas = new javax.swing.JLabel();
        jbtnAñadirTornillo = new javax.swing.JButton();
        jbtnAñadirLlanta = new javax.swing.JButton();
        jbtnAñadirValvula = new javax.swing.JButton();
        jtxtTornillo = new javax.swing.JTextField();
        jtxtLLanta = new javax.swing.JTextField();
        jtxtValvula = new javax.swing.JTextField();
        jlblTituloNeumaticos = new javax.swing.JLabel();
        jtxtNeumatico = new javax.swing.JTextField();
        jbtnAñadirNeumatico = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jtblComponentes = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jlblTitulo = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblTornillos = new javax.swing.JTable();
        jlblRTituloTornillo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtblValvulas = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtblnNeumaticos = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtblRuedas = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblLlantas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema");
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        JpnlInsersion1.setBackground(new java.awt.Color(255, 255, 255));
        JpnlInsersion1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel12.setText("REPUESTO ");

        jcbxRespuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbxRespuestosActionPerformed(evt);
            }
        });

        jLabel13.setText("CODIGO");

        jLabel14.setText("MARCA ");

        jLabel15.setText("PRECIO");

        jLabel16.setText("TAMAÑO");

        jLabel17.setText("TIPO");

        jbtnAñadirRepuesto.setText("Añadir Repuesto");
        jbtnAñadirRepuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAñadirRepuestoActionPerformed(evt);
            }
        });

        jLabel18.setText("REPUESTOS");

        javax.swing.GroupLayout JpnlInsersion1Layout = new javax.swing.GroupLayout(JpnlInsersion1);
        JpnlInsersion1.setLayout(JpnlInsersion1Layout);
        JpnlInsersion1Layout.setHorizontalGroup(
            JpnlInsersion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnlInsersion1Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(JpnlInsersion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jcbxRespuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JpnlInsersion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel13)
                        .addComponent(jtxtRepuestoCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(JpnlInsersion1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpnlInsersion1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JpnlInsersion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpnlInsersion1Layout.createSequentialGroup()
                        .addGroup(JpnlInsersion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JpnlInsersion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jtxtRepuestoTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(JpnlInsersion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jtxtRepuestoMarca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel16))
                        .addGap(48, 48, 48)
                        .addGroup(JpnlInsersion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jtxtRepuestoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(jtxtRepuestoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JpnlInsersion1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jbtnAñadirRepuesto)))
                .addContainerGap())
        );
        JpnlInsersion1Layout.setVerticalGroup(
            JpnlInsersion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnlInsersion1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbxRespuestos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtRepuestoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(JpnlInsersion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JpnlInsersion1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtRepuestoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JpnlInsersion1Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtRepuestoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(JpnlInsersion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpnlInsersion1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtRepuestoTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JpnlInsersion1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtRepuestoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnAñadirRepuesto)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        JpnlInsersion.setBackground(new java.awt.Color(255, 255, 255));
        JpnlInsersion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("COMPONENTE ");

        jcbxComponentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbxComponentesActionPerformed(evt);
            }
        });

        jLabel2.setText("CODIGO");

        jLabel7.setText("MARCA");

        jLabel8.setText("PRECIO");

        jLabel9.setText("TAMAÑO");

        jbtnConstruirComponente.setText("Construir Componente");
        jbtnConstruirComponente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConstruirComponenteActionPerformed(evt);
            }
        });

        jLabel11.setText("CONSTRUCCION DE COMPONENTES");

        jlblTituloTornillos.setText("TORNILLOS");
        jlblTituloTornillos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlblTituloLlantas.setText("LLANTAS");
        jlblTituloLlantas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlblTituloValvulas.setText("VALVULAS");
        jlblTituloValvulas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbtnAñadirTornillo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtnAñadirTornillo.setText("Agregar");
        jbtnAñadirTornillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAñadirTornilloActionPerformed(evt);
            }
        });

        jbtnAñadirLlanta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtnAñadirLlanta.setText("Agregar");
        jbtnAñadirLlanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAñadirLlantaActionPerformed(evt);
            }
        });

        jbtnAñadirValvula.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtnAñadirValvula.setText("Agregar");
        jbtnAñadirValvula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAñadirValvulaActionPerformed(evt);
            }
        });

        jlblTituloNeumaticos.setText("NEUMATICOS");
        jlblTituloNeumaticos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbtnAñadirNeumatico.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtnAñadirNeumatico.setText("Agregar");
        jbtnAñadirNeumatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAñadirNeumaticoActionPerformed(evt);
            }
        });

        jtblComponentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane6.setViewportView(jtblComponentes);

        jButton1.setText("Agregar Seguro");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpnlInsersionLayout = new javax.swing.GroupLayout(JpnlInsersion);
        JpnlInsersion.setLayout(JpnlInsersionLayout);
        JpnlInsersionLayout.setHorizontalGroup(
            JpnlInsersionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnlInsersionLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(JpnlInsersionLayout.createSequentialGroup()
                .addGroup(JpnlInsersionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpnlInsersionLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(JpnlInsersionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JpnlInsersionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(JpnlInsersionLayout.createSequentialGroup()
                                    .addGroup(JpnlInsersionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jtxtTornillo)
                                        .addComponent(jlblTituloTornillos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(JpnlInsersionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtxtLLanta)
                                        .addComponent(jlblTituloLlantas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(JpnlInsersionLayout.createSequentialGroup()
                                    .addComponent(jbtnAñadirTornillo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jbtnAñadirLlanta)))
                            .addGroup(JpnlInsersionLayout.createSequentialGroup()
                                .addGroup(JpnlInsersionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtxtValvula, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtnAñadirValvula, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlblTituloValvulas, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(JpnlInsersionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jlblTituloNeumaticos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtxtNeumatico)
                                    .addComponent(jbtnAñadirNeumatico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(JpnlInsersionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(JpnlInsersionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnConstruirComponente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JpnlInsersionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(JpnlInsersionLayout.createSequentialGroup()
                        .addGroup(JpnlInsersionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jtxtComponenteCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(JpnlInsersionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtComponenteMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(JpnlInsersionLayout.createSequentialGroup()
                        .addGroup(JpnlInsersionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtComponenteTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(JpnlInsersionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jtxtComponentePrecio)))
                    .addComponent(jcbxComponentes, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        JpnlInsersionLayout.setVerticalGroup(
            JpnlInsersionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnlInsersionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGroup(JpnlInsersionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JpnlInsersionLayout.createSequentialGroup()
                        .addGroup(JpnlInsersionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JpnlInsersionLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(JpnlInsersionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jlblTituloLlantas)
                                    .addComponent(jlblTituloTornillos))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(JpnlInsersionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtTornillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtLLanta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(JpnlInsersionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jbtnAñadirTornillo)
                                    .addComponent(jbtnAñadirLlanta))
                                .addGap(29, 29, 29)
                                .addComponent(jlblTituloValvulas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxtValvula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtnAñadirValvula))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpnlInsersionLayout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(jlblTituloNeumaticos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxtNeumatico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtnAñadirNeumatico)))
                        .addGap(48, 48, 48)
                        .addComponent(jbtnConstruirComponente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(JpnlInsersionLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbxComponentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(JpnlInsersionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(JpnlInsersionLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(41, 41, 41))
                            .addGroup(JpnlInsersionLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(JpnlInsersionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtxtComponenteMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtComponenteCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(JpnlInsersionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(JpnlInsersionLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtComponenteTamaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JpnlInsersionLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtComponentePrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jlblTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jlblTitulo.setText("SISTEMA DE REPUESTOS NEUMATICOS");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jtblTornillos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jtblTornillos);

        jlblRTituloTornillo.setText("TORNILLOS");

        jLabel5.setText("VALVULAS");

        jtblValvulas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(jtblValvulas);

        jLabel6.setText("NEUMÁTICOS");

        jtblnNeumaticos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(jtblnNeumaticos);

        jLabel19.setText("COMPONENTES");

        jLabel20.setText("REPUESTOS");

        jLabel4.setText("RUEDAS");

        jtblRuedas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jtblRuedas);

        jLabel3.setText("LLANTA");

        jtblLlantas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtblLlantas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlblRTituloTornillo)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(130, 130, 130)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1)))
                            .addComponent(jLabel19))
                        .addGap(80, 80, 80))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlblRTituloTornillo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(1, 1, 1)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel3)
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jScrollPane7.setViewportView(jPanel1);

        jDesktopPane1.setLayer(JpnlInsersion1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(JpnlInsersion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jlblTitulo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(JpnlInsersion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JpnlInsersion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 1177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(342, 342, 342)
                .addComponent(jlblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jlblTitulo)
                .addGap(52, 52, 52)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JpnlInsersion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JpnlInsersion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(225, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnConstruirComponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConstruirComponenteActionPerformed
        construccion();
    }//GEN-LAST:event_jbtnConstruirComponenteActionPerformed

    private void jbtnAñadirRepuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAñadirRepuestoActionPerformed
        switch (this.jcbxRespuestos.getSelectedIndex()) {
            case 1:
                agregarTornillos();
                break;
            case 2:
                agregarValvula();
                break;
            case 3:
                agregarNeumatico();
                break;
            default:
                break;
        }

    }//GEN-LAST:event_jbtnAñadirRepuestoActionPerformed

    private void jcbxRespuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbxRespuestosActionPerformed
        agregarRepuestos();
    }//GEN-LAST:event_jcbxRespuestosActionPerformed

    private void jcbxComponentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbxComponentesActionPerformed
        agregarComponentes();
    }//GEN-LAST:event_jcbxComponentesActionPerformed

    private void jbtnAñadirTornilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAñadirTornilloActionPerformed
        añadirTornillo(this.jtxtTornillo.getText());
    }//GEN-LAST:event_jbtnAñadirTornilloActionPerformed

    private void jbtnAñadirLlantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAñadirLlantaActionPerformed
        añadirLlanta(this.jtxtLLanta.getText());
    }//GEN-LAST:event_jbtnAñadirLlantaActionPerformed

    private void jbtnAñadirValvulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAñadirValvulaActionPerformed
        añadirValvula(this.jtxtValvula.getText());
    }//GEN-LAST:event_jbtnAñadirValvulaActionPerformed

    private void jbtnAñadirNeumaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAñadirNeumaticoActionPerformed
        añadirNeumatico(this.jtxtNeumatico.getText());
    }//GEN-LAST:event_jbtnAñadirNeumaticoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Seguro seguro = new Seguro();
        seguro.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpnlInsersion;
    private javax.swing.JPanel JpnlInsersion1;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JButton jbtnAñadirLlanta;
    private javax.swing.JButton jbtnAñadirNeumatico;
    private javax.swing.JButton jbtnAñadirRepuesto;
    private javax.swing.JButton jbtnAñadirTornillo;
    private javax.swing.JButton jbtnAñadirValvula;
    private javax.swing.JButton jbtnConstruirComponente;
    private javax.swing.JComboBox<String> jcbxComponentes;
    private javax.swing.JComboBox<String> jcbxRespuestos;
    private javax.swing.JLabel jlblRTituloTornillo;
    private javax.swing.JLabel jlblTitulo;
    private javax.swing.JLabel jlblTituloLlantas;
    private javax.swing.JLabel jlblTituloNeumaticos;
    private javax.swing.JLabel jlblTituloTornillos;
    private javax.swing.JLabel jlblTituloValvulas;
    private javax.swing.JTable jtblComponentes;
    private javax.swing.JTable jtblLlantas;
    private javax.swing.JTable jtblRuedas;
    private javax.swing.JTable jtblTornillos;
    private javax.swing.JTable jtblValvulas;
    private javax.swing.JTable jtblnNeumaticos;
    private javax.swing.JTextField jtxtComponenteCodigo;
    private javax.swing.JTextField jtxtComponenteMarca;
    private javax.swing.JTextField jtxtComponentePrecio;
    private javax.swing.JTextField jtxtComponenteTamaño;
    private javax.swing.JTextField jtxtLLanta;
    private javax.swing.JTextField jtxtNeumatico;
    private javax.swing.JTextField jtxtRepuestoCodigo;
    private javax.swing.JTextField jtxtRepuestoMarca;
    private javax.swing.JTextField jtxtRepuestoPrecio;
    private javax.swing.JTextField jtxtRepuestoTamaño;
    private javax.swing.JTextField jtxtRepuestoTipo;
    private javax.swing.JTextField jtxtTornillo;
    private javax.swing.JTextField jtxtValvula;
    // End of variables declaration//GEN-END:variables

    private final Conexion conexion = new Conexion();
    private final Connection connection = conexion.conectar();

    private DefaultTableModel modeloTornillos;
    private DefaultTableModel modeloLlantas;
    private DefaultTableModel modeloValvulas;
    private DefaultTableModel modeloNeumaticos;
    private DefaultTableModel modeloRuedas;
    private DefaultTableModel modeloComponentes;

    Integer fila;

    private void cargarTornillos() {
        try {
            String[] titulos = {"CÓDIGO", "MARCA", "PRECIO"};
            this.modeloTornillos = new DefaultTableModel(null, titulos);

            String[] registros = new String[4];

            if (connection != null) {
                String sql = "SELECT * FROM TORNILLOS";
                Statement statement = connection.createStatement();
                ResultSet resultSet = statement.executeQuery(sql);

                while (resultSet.next()) {
                    registros[0] = resultSet.getString("CODIGO");
                    registros[1] = resultSet.getString("MARCA");
                    registros[2] = resultSet.getString("PRECIO");
                    this.modeloTornillos.addRow(registros);
                }
                this.jtblTornillos.setModel(this.modeloTornillos);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error:  " + ex);
        }
    }

    private void cargarLlantas() {
        try {
            String[] titulos = {"CÓDIGO", "MARCA", "TAMAÑO", "PRECIO", "TORNILLOS"};
            this.modeloLlantas = new DefaultTableModel(null, titulos);

            String[] registros = new String[5];

            if (connection != null) {
                String sql = "SELECT * FROM LLANTAS";
                Statement statement = connection.createStatement();
                ResultSet resultSet = statement.executeQuery(sql);

                while (resultSet.next()) {
                    registros[0] = resultSet.getString("CODIGO");
                    registros[1] = resultSet.getString("MARCA");
                    registros[2] = resultSet.getString("TAMAÑO");
                    registros[3] = resultSet.getString("PRECIO");
                    registros[4] = resultSet.getString("TORNILLOS");

                    this.modeloLlantas.addRow(registros);
                }
                this.jtblLlantas.setModel(this.modeloLlantas);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error:  " + ex);
        }
    }

    private void cargarValvulas() {
        try {
            String[] titulos = {"CÓDIGO", "TIPO", "PRECIO"};
            this.modeloValvulas = new DefaultTableModel(null, titulos);

            String[] registros = new String[3];

            if (connection != null) {
                String sql = "SELECT * FROM VALVULAS";
                Statement statement = connection.createStatement();
                ResultSet resultSet = statement.executeQuery(sql);

                while (resultSet.next()) {
                    registros[0] = resultSet.getString("CODIGO");
                    registros[1] = resultSet.getString("TIPO");
                    registros[2] = resultSet.getString("PRECIO");

                    this.modeloValvulas.addRow(registros);
                }
                this.jtblValvulas.setModel(this.modeloValvulas);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error:  " + ex);
        }
    }

    private void cargarNeumaticos() {
        try {
            String[] titulos = {"CÓDIGO", "MARCA", "TAMAÑO", "PRECIO"};
            this.modeloNeumaticos = new DefaultTableModel(null, titulos);

            String[] registros = new String[4];

            if (connection != null) {
                String sql = "SELECT * FROM NEUMATICOS";
                Statement statement = connection.createStatement();
                ResultSet resultSet = statement.executeQuery(sql);

                while (resultSet.next()) {
                    registros[0] = resultSet.getString("CODIGO");
                    registros[1] = resultSet.getString("MARCA");
                    registros[2] = resultSet.getString("TAMAÑO");
                    registros[3] = resultSet.getString("PRECIO");

                    this.modeloNeumaticos.addRow(registros);
                }
                this.jtblnNeumaticos.setModel(this.modeloNeumaticos);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error:  " + ex);
        }
    }

    private void cargarRuedas() {
        try {
            String[] titulos = {"CÓDIGO", "TAMAÑO", "LLANTA", "NEUMÁTICO", "PRECIO"};
            this.modeloRuedas = new DefaultTableModel(null, titulos);

            String[] registros = new String[5];

            if (connection != null) {
                String sql = "SELECT * FROM RUEDAS";
                Statement statement = connection.createStatement();
                ResultSet resultSet = statement.executeQuery(sql);

                while (resultSet.next()) {
                    registros[0] = resultSet.getString("CODIGO");
                    registros[1] = resultSet.getString("TAMAÑO");
                    registros[2] = resultSet.getString("LLANTA");
                    registros[3] = resultSet.getString("NEUMATICO");
                    registros[4] = resultSet.getString("PRECIO");

                    this.modeloRuedas.addRow(registros);
                }
                this.jtblRuedas.setModel(this.modeloRuedas);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error:  " + ex);
        }
    }

    private void cargarRepuestos() {
        this.jcbxRespuestos.addItem(" ");
        this.jcbxRespuestos.addItem("Tornillos");
        this.jcbxRespuestos.addItem("Válvulas");
        this.jcbxRespuestos.addItem("Neumáticos");
    }

    private void cargarComponentes() {
        this.jcbxComponentes.addItem(" ");
        this.jcbxComponentes.addItem("Llanta");
        this.jcbxComponentes.addItem("Rueda");
    }

    private void agregarRepuestos() {
        switch (this.jcbxRespuestos.getSelectedIndex()) {
            case 1:
                this.jtxtRepuestoCodigo.setEnabled(true);
                this.jtxtRepuestoMarca.setEnabled(true);
                this.jtxtRepuestoPrecio.setEnabled(true);
                this.jtxtRepuestoTipo.setEnabled(false);
                this.jtxtRepuestoTamaño.setEnabled(false);
                break;
            case 2:
                this.jtxtRepuestoCodigo.setEnabled(true);
                this.jtxtRepuestoTipo.setEnabled(true);
                this.jtxtRepuestoPrecio.setEnabled(true);
                this.jtxtRepuestoTamaño.setEnabled(false);
                this.jtxtRepuestoMarca.setEnabled(false);
                break;
            case 3:
                this.jtxtRepuestoCodigo.setEnabled(true);
                this.jtxtRepuestoMarca.setEnabled(true);
                this.jtxtRepuestoTamaño.setEnabled(true);
                this.jtxtRepuestoPrecio.setEnabled(false);
                this.jtxtRepuestoTipo.setEnabled(false);
                break;
            default:
                this.jtxtRepuestoCodigo.setEnabled(false);
                this.jtxtRepuestoMarca.setEnabled(false);
                this.jtxtRepuestoTipo.setEnabled(false);
                this.jtxtRepuestoTamaño.setEnabled(false);
                this.jtxtRepuestoPrecio.setEnabled(false);
                break;
        }

    }

    private void agregarComponentes() {
        switch (this.jcbxComponentes.getSelectedIndex()) {
            case 1:
                this.jtxtComponenteCodigo.setEnabled(true);
                this.jtxtComponenteMarca.setEnabled(true);
                this.jtxtComponenteTamaño.setEnabled(true);
                this.jtxtComponentePrecio.setEnabled(true);

                this.jbtnConstruirComponente.setEnabled(true);
                cargarTablaComponenteLlanta();
                bloqueoLlantas();
                break;
            case 2:
                this.jtxtComponenteCodigo.setEnabled(true);
                this.jtxtComponenteTamaño.setEnabled(true);
                this.jtxtComponentePrecio.setEnabled(true);
                this.jtxtComponenteMarca.setEnabled(false);

                this.jbtnConstruirComponente.setEnabled(true);
                cargarTablaComponenteLlantaRueda();
                bloqueoRuedas();
                break;
            default:
                this.jtxtComponenteCodigo.setEnabled(false);
                this.jtxtComponenteMarca.setEnabled(false);
                this.jtxtComponenteTamaño.setEnabled(false);
                this.jtxtComponentePrecio.setEnabled(false);
                bloqueoTotal();
                break;
        }

    }

    private void agregarTornillos() {
        try {
            String sql = "INSERT INTO TORNILLOS(CODIGO, MARCA, PRECIO) VALUES(?, ?, ?)";
            if (this.jtxtRepuestoCodigo.getText().equals("") || this.jtxtRepuestoMarca.getText().equals("")
                    || this.jtxtRepuestoPrecio.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Inserte Datos o Datos Incompletos");
                this.jtxtRepuestoCodigo.requestFocus();
            } else {
                PreparedStatement preparedStatement = connection.prepareStatement(sql);
                preparedStatement.setString(1, this.jtxtRepuestoCodigo.getText());
                preparedStatement.setString(2, this.jtxtRepuestoMarca.getText().toUpperCase());
                preparedStatement.setString(3, this.jtxtRepuestoPrecio.getText());

                int n = preparedStatement.executeUpdate();
                if (n > 0) {
                    JOptionPane.showMessageDialog(this, "¡Inserción Exitosa!");
                }
                cargarTornillos();
                limpiar();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex);
        }
    }

    private void limpiar() {
        this.jtxtRepuestoCodigo.setText("");
        this.jtxtRepuestoMarca.setText("");
        this.jtxtRepuestoTipo.setText("");
        this.jtxtRepuestoTamaño.setText("");
        this.jtxtRepuestoPrecio.setText("");
    }

    private void agregarValvula() {
        try {
            String sql = "INSERT INTO VALVULAS(CODIGO, TIPO, PRECIO) VALUES(?, ?, ?)";
            if (this.jtxtRepuestoCodigo.getText().equals("") || this.jtxtRepuestoTipo.getText().equals("")
                    || this.jtxtRepuestoPrecio.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Inserte Datos o Datos Incompletos");
                this.jtxtRepuestoCodigo.requestFocus();
            } else {
                PreparedStatement preparedStatement = connection.prepareStatement(sql);
                preparedStatement.setString(1, this.jtxtRepuestoCodigo.getText());
                preparedStatement.setString(2, this.jtxtRepuestoTipo.getText().toUpperCase());
                preparedStatement.setString(3, this.jtxtRepuestoPrecio.getText());

                int n = preparedStatement.executeUpdate();
                if (n > 0) {
                    JOptionPane.showMessageDialog(this, "¡Inserción Exitosa!");
                }
                cargarValvulas();
                limpiar();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex);
        }
    }

    private void agregarNeumatico() {
        try {
            String sql = "INSERT INTO NEUMATICOS(CODIGO, MARCA, TAMAÑO, PRECIO) VALUES(?, ?, ?, ?)";
            if (this.jtxtRepuestoCodigo.getText().equals("") || this.jtxtRepuestoMarca.getText().equals("")
                    || this.jtxtRepuestoTamaño.getText().equals("")
                    || this.jtxtRepuestoPrecio.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Inserte Datos o Datos Incompletos");
                this.jtxtRepuestoCodigo.requestFocus();
            } else {
                PreparedStatement preparedStatement = connection.prepareStatement(sql);
                preparedStatement.setString(1, this.jtxtRepuestoCodigo.getText());
                preparedStatement.setString(2, this.jtxtRepuestoMarca.getText().toUpperCase());
                preparedStatement.setString(3, this.jtxtRepuestoTamaño.getText());
                preparedStatement.setString(4, this.jtxtRepuestoPrecio.getText());

                int n = preparedStatement.executeUpdate();
                if (n > 0) {
                    JOptionPane.showMessageDialog(this, "¡Inserción Exitosa!");
                }
                cargarNeumaticos();
                limpiar();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex);
        }
    }

    public void seleccionarTornillo() {
        this.jtblTornillos.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
            if (jtblTornillos.getSelectedRow() != -1) {
                fila = jtblTornillos.getSelectedRow();
                jtxtTornillo.setText(jtblTornillos.getValueAt(fila, 0).toString());
            }
        });
    }

    public void seleccionarLlanta() {
        this.jtblLlantas.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
            if (jtblLlantas.getSelectedRow() != -1) {
                fila = jtblLlantas.getSelectedRow();
                jtxtLLanta.setText(jtblLlantas.getValueAt(fila, 0).toString());
            }
        });
    }

    public void seleccionarValvula() {
        this.jtblValvulas.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
            if (jtblValvulas.getSelectedRow() != -1) {
                fila = jtblValvulas.getSelectedRow();
                jtxtValvula.setText(jtblValvulas.getValueAt(fila, 0).toString());
            }
        });
    }

    public void seleccionarNeumatico() {
        this.jtblnNeumaticos.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
            if (jtblLlantas.getSelectedRow() != -1) {
                fila = jtblnNeumaticos.getSelectedRow();
                jtxtNeumatico.setText(jtblnNeumaticos.getValueAt(fila, 0).toString());
            }
        });
    }

    private void bloqueoLlantas() {
        this.jlblTituloTornillos.setEnabled(true);
        this.jtxtTornillo.setEnabled(true);
        this.jbtnAñadirTornillo.setEnabled(true);

        this.jlblTituloLlantas.setEnabled(false);
        this.jtxtLLanta.setEnabled(false);
        this.jbtnAñadirLlanta.setEnabled(false);

        this.jlblTituloValvulas.setEnabled(false);
        this.jtxtValvula.setEnabled(false);
        this.jbtnAñadirValvula.setEnabled(false);

        this.jlblTituloNeumaticos.setEnabled(false);
        this.jtxtNeumatico.setEnabled(false);
        this.jbtnAñadirNeumatico.setEnabled(false);
    }

    private void bloqueoRuedas() {
        this.jlblTituloTornillos.setEnabled(false);
        this.jtxtTornillo.setEnabled(false);
        this.jbtnAñadirTornillo.setEnabled(false);

        this.jlblTituloLlantas.setEnabled(true);
        this.jtxtLLanta.setEnabled(true);
        this.jbtnAñadirLlanta.setEnabled(true);

        this.jlblTituloValvulas.setEnabled(true);
        this.jtxtValvula.setEnabled(true);
        this.jbtnAñadirValvula.setEnabled(true);

        this.jlblTituloNeumaticos.setEnabled(true);
        this.jtxtNeumatico.setEnabled(true);
        this.jbtnAñadirNeumatico.setEnabled(true);
    }

    private void bloqueoTotal() {
        this.jlblTituloTornillos.setEnabled(false);
        this.jtxtTornillo.setEnabled(false);
        this.jbtnAñadirTornillo.setEnabled(false);

        this.jlblTituloLlantas.setEnabled(false);
        this.jtxtLLanta.setEnabled(false);
        this.jbtnAñadirLlanta.setEnabled(false);

        this.jlblTituloValvulas.setEnabled(false);
        this.jtxtValvula.setEnabled(false);
        this.jbtnAñadirValvula.setEnabled(false);

        this.jlblTituloNeumaticos.setEnabled(false);
        this.jtxtNeumatico.setEnabled(false);
        this.jbtnAñadirNeumatico.setEnabled(false);

        this.jbtnConstruirComponente.setEnabled(false);
    }

    private void cargarTablaComponenteLlanta() {
        String[] titulos = {"CÓDIGO", "MARCA", "PRECIO"};
        this.modeloComponentes = new DefaultTableModel(null, titulos);
        this.jtblComponentes.setModel(this.modeloComponentes);
    }

    private void cargarTablaComponenteLlantaRueda() {
        String[] titulos = {"CÓDIGO", "MARCA", "TIPO", "TAMAÑO", "PRECIO"};
        this.modeloComponentes = new DefaultTableModel(null, titulos);
        this.jtblComponentes.setModel(this.modeloComponentes);
    }

    private void añadirTornillo(String tornillo) {
        try {
            String[] registros = new String[3];
            if (connection != null) {
                String sql = "SELECT * FROM TORNILLOS WHERE CODIGO = '" + tornillo + "'";
                Statement statement = connection.createStatement();
                ResultSet resultSet = statement.executeQuery(sql);

                while (resultSet.next()) {
                    registros[0] = resultSet.getString("CODIGO");
                    registros[1] = resultSet.getString("MARCA");
                    registros[2] = resultSet.getString("PRECIO");
                    this.modeloComponentes.addRow(registros);
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error:  " + ex);
        }
    }

    private void añadirLlanta(String llanta) {
        try {
            String[] registros = new String[5];
            if (connection != null) {
                String sql = "SELECT * FROM LLANTAS WHERE CODIGO = '" + llanta + "'";
                Statement statement = connection.createStatement();
                ResultSet resultSet = statement.executeQuery(sql);

                while (resultSet.next()) {
                    registros[0] = resultSet.getString("CODIGO");
                    registros[1] = resultSet.getString("MARCA");
                    registros[3] = resultSet.getString("TAMAÑO");
                    registros[4] = resultSet.getString("PRECIO");

                    this.modeloComponentes.addRow(registros);
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error:  " + ex);
        }
    }

    private void añadirValvula(String valvula) {
        try {
            String[] registros = new String[5];
            if (connection != null) {
                String sql = "SELECT * FROM VALVULAS WHERE CODIGO = '" + valvula + "'";
                Statement statement = connection.createStatement();
                ResultSet resultSet = statement.executeQuery(sql);

                while (resultSet.next()) {
                    registros[0] = resultSet.getString("CODIGO");
                    registros[2] = resultSet.getString("TIPO");
                    registros[4] = resultSet.getString("PRECIO");
                    this.modeloComponentes.addRow(registros);
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error:  " + ex);
        }
    }

    private void añadirNeumatico(String neumatico) {
        try {
            String[] registros = new String[5];
            if (connection != null) {
                String sql = "SELECT * FROM NEUMATICOS WHERE CODIGO = '" + neumatico + "'";
                Statement statement = connection.createStatement();
                ResultSet resultSet = statement.executeQuery(sql);

                while (resultSet.next()) {
                    registros[0] = resultSet.getString("CODIGO");
                    registros[1] = resultSet.getString("MARCA");
                    registros[3] = resultSet.getString("TAMAÑO");
                    registros[4] = resultSet.getString("PRECIO");
                    this.modeloComponentes.addRow(registros);
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error:  " + ex);
        }
    }

    private void construccion() {
        switch (this.jcbxComponentes.getSelectedIndex()) {
            case 1:
                construccionLlanta();
                break;
            case 2:
                construccionRueda();
                break;
            default:
                this.jbtnConstruirComponente.setEnabled(false);
                break;
        }

    }

    private void construccionLlanta() {
        IRecambio llanta = new CompuestoRecambio(this.jtxtComponenteCodigo.getText(), this.jtxtComponenteMarca.getText(),
                this.jtxtComponenteTamaño.getText(), Float.valueOf(this.jtxtComponentePrecio.getText()));

        for (int i = 0; i < this.jtblComponentes.getRowCount(); i++) {
            IRecambio tornillo = new ElementoRecambio(this.jtblComponentes.getValueAt(i, 0).toString(),
                    this.jtblComponentes.getValueAt(i, 1).toString(),
                    Float.valueOf(this.jtblComponentes.getValueAt(i, 2).toString()));
            llanta.addComponenteRecambio(tornillo);
        }
        insertarLlanta();
        cargarLlantas();
    }

    private void insertarLlanta() {
        try {
            String sql = "INSERT INTO LLANTAS(CODIGO, MARCA, TAMAÑO, PRECIO, TORNILLOS) VALUES(?, ?, ?, ?, ?)";
            if (this.jtxtComponenteCodigo.getText().equals("") || this.jtxtComponenteMarca.getText().equals("")
                    || this.jtxtComponenteTamaño.getText().equals("")
                    || this.jtxtComponentePrecio.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Inserte Datos o Datos Incompletos");
                this.jtxtComponenteCodigo.requestFocus();
            } else {
                PreparedStatement psd = connection.prepareStatement(sql);
                psd.setString(1, this.jtxtComponenteCodigo.getText().toUpperCase());
                psd.setString(2, this.jtxtComponenteMarca.getText().toUpperCase());
                psd.setString(3, this.jtxtComponenteTamaño.getText().toUpperCase());
                psd.setString(4, this.jtxtComponentePrecio.getText());

                int n = psd.executeUpdate();
                if (n > 0) {
                    JOptionPane.showMessageDialog(this, "¡Inserción Exitosa!");
                }
                cargarLlantas();
                limpiar();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Fallido " + ex);
        }
    }

    private void construccionRueda() {
        IRecambio llanta = new CompuestoRecambio(this.jtxtComponenteCodigo.getText(), this.jtxtComponenteMarca.getText(),
                this.jtxtComponenteTamaño.getText(), Float.valueOf(this.jtxtComponentePrecio.getText()));

        for (int i = 0; i < this.jtblComponentes.getRowCount(); i++) {
            IRecambio tornillo = new ElementoRecambio(this.jtblComponentes.getValueAt(i, 0).toString(),
                    this.jtblComponentes.getValueAt(i, 1).toString(),
                    Float.valueOf(this.jtblComponentes.getValueAt(i, 2).toString()));
            llanta.addComponenteRecambio(tornillo);
        }
        insertarRueda();
        cargarRuedas();
    }

    private void insertarRueda() {
        try {
            String sql = "INSERT INTO LLANTAS(CODIGO, MARCA, TAMAÑO, PRECIO, TORNILLOS) VALUES(?, ?, ?, ?, ?)";
            if (this.jtxtComponenteCodigo.getText().equals("") || this.jtxtComponenteMarca.getText().equals("")
                    || this.jtxtComponenteTamaño.getText().equals("")
                    || this.jtxtComponentePrecio.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Inserte Datos o Datos Incompletos");
                this.jtxtComponenteCodigo.requestFocus();
            } else {
                PreparedStatement psd = connection.prepareStatement(sql);
                psd.setString(1, this.jtxtComponenteCodigo.getText().toUpperCase());
                psd.setString(2, this.jtxtComponenteMarca.getText().toUpperCase());
                psd.setString(3, this.jtxtComponenteTamaño.getText().toUpperCase());
                psd.setString(4, this.jtxtComponentePrecio.getText());

                int n = psd.executeUpdate();
                if (n > 0) {
                    JOptionPane.showMessageDialog(this, "¡Inserción Exitosa!");
                }
                cargarLlantas();
                limpiar();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Fallido " + ex);
        }
    }
}
